### ISSUE TITLE
examples needed 2

### ISSUE THREAD

**Issue by matti** [socketry/async-http#14]
Like in #12 these async-* really need more examples.

I'm having hard time figuring out how to post a json to a server.

And I think I've done my Async tutorial already: https://github.com/matti/async-nats

**Comment by matti** [comment]
^-- sorry for being so negative, I just have been digging a lot of async-* source lately...

**Comment by ioquatix** [comment]
It’s good I am busy now but will review later.

**Comment by matti** [comment]
created a concrete issue instead #15
