### ISSUE TITLE
Add an example of POSTing a file with a chunked encoding

### ISSUE THREAD

**Issue by ainar-g** [socketry/async-http#16]
I couldn't quite figure out how to do that. `Async::HTTP::Body::Chunked` seems to be used in reading a chunked response, not sending it to a remote server. It would be nice to have an example.

**Comment by ioquatix** [comment]
Do you need to explicitly use chunked encoding? Can you give me a better idea of what you are trying to do?

**Comment by ainar-g** [comment]
Basically, I want to upload Rails's `Tempfile` into a third-party server without reading the whole file into RAM. Right now I am using `body_stream` from the native `Net::HTTP`.

**Comment by ioquatix** [comment]
You can use https://github.com/socketry/protocol-http/blob/master/lib/protocol/http/body/file.rb or implement something similar. It should stream in chunks.
