### ISSUE TITLE
Support 2.3

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-http#24]
@ganmacs More work is required to support this on 2.3

https://travis-ci.org/socketry/async-http/jobs/556300746

Can you submit a PR to `protocol-http2` similar to the existing extension to add `Array#sum` and test? I can't even compile 2.3 locally, so if you can test it that would be great.

**Comment by ioquatix** [comment]
@ganmacs, do you think you can also add specs to protocol-http2 that hit the breaking cases? Even if they are simple, I can improve them, as long as we have something to prevent regressions.

**Comment by ganmacs** [comment]
Okay. I'll do add the monkey patch for `Array#sum` and the test for it to protocol-http2.

**Comment by ioquatix** [comment]
Awesome, looking forward to getting it.
