### ISSUE TITLE
Webmock Gem

### ISSUE THREAD

**Issue by tleish** [socketry/async-http#34]
I'm trying to use VCR with Webmock and wondering if this is a viable solution with async-http.

**Comment by tleish** [comment]
I think this is the code that is supposed to handle it in Webmock, but having issues... so closing here as I don't think it's an async-http issue, but rather code in Webmock.

**Comment by tleish** [comment]
FYI, looks like issue has already been reported here: https://github.com/bblimke/webmock/issues/858

**Comment by ioquatix** [comment]
Thanks for the links.
