### ISSUE TITLE
Kwargs instead of positional args

### ISSUE THREAD

**Issue by swrobel** [socketry/async-http#49]
I'm curious why the decision was made to [take positional](https://github.com/socketry/async-http/blob/v0.51.2/lib/async/http/internet.rb#L65), rather than keyword args in a modern library like this.

```ruby
internet.post("https://httpbin.org/anything", body: body)
```

seems preferable to

```ruby
internet.post("https://httpbin.org/anything", nil, body)
```

**Comment by ioquatix** [comment]
Positional args were at the time slightly more efficient and predictable than kwargs, but I'd be open to changing this if you think there is a significant improvement to interface ergonomics.

**Comment by ioquatix** [comment]
I've changed `Async::HTTP::Client` and `Async::HTTP::Server` to use keyword arguments.

I'm not sure we can easily change these methods without breaking a ton of stuff.

**Comment by ioquatix** [comment]
If we think the ergonimics outweighs the overhead, something like this can work:

```ruby
def get(_headers = nil, _body = nil, headers: _headers, body: _body)
  # ...
end
```

and be backwards compatible. As long as the performance cost is insignificant, I'd be willing to accept this for the `def get` / `post` / `patch` convenience methods for `Async::HTTP::Internet` (but probably not `call`).

**Comment by ioquatix** [comment]
Okay, this is now supported.

See https://socketry.github.io/protocol-http/releases/index#request%5B%5D-and-response%5B%5D-keyword-arguments for details. It works for all methods including `Internet#call`.
