### ISSUE TITLE
Unexpected response headers in HTTP1.0

### ISSUE THREAD

**Issue by guppy0356** [socketry/async-http#57]
I try to contribute to [webmock](https://github.com/bblimke/webmock) to fix InvalidURIError on https://github.com/bblimke/webmock/pull/890. I found unexpected response headers in Travis CI result.
👉  https://travis-ci.org/github/bblimke/webmock/jobs/696308825

Is it normal for response headers to contain `keep-alive` in http1.0 ? I think https://github.com/socketry/async-http/commit/a832d02cdcbdf4c64570cabd2008fc1a3d4c7daa has affect this response.

**Comment by ioquatix** [comment]
If possible can you show me the full request and response details.

Yes, HTTP/1.0 requires `Connection: keep-alive` for persistent connections.

**Comment by ioquatix** [comment]
That looks correct to me. It would probably make sense to scrub connection headers (and per-hop)
 headers from the response if you are computing a checksum/hash.

**Comment by guppy0356** [comment]
@ioquatix 
thank you for your cooperation.

**Comment by ioquatix** [comment]
You are most welcome!
