### ISSUE TITLE
latest releases missing on rubygems

### ISSUE THREAD

**Issue by bastelfreak** [socketry/async-http#81]
Hi,
I noticed that the latest release on rubygems, 0.9.0, has no license set in the gemspec file. This is now present in the master branch and there are many git tags without a rubygems release. Could you publish to rubygems again?

**Comment by olleolleolle** [comment]
👋 Hello, https://rubygems.org/gems/async-http seems to have a June 2021 release 

<img width="107" alt="bild" src="https://user-images.githubusercontent.com/211/122029513-38363b00-cdcd-11eb-9187-b41679aba926.png">


https://rubygems.org/gems/async-http/versions/0.56.3

Does that clear things up?

**Comment by bastelfreak** [comment]
ah stupid me. I was talking about https://github.com/socketry/async-http-faraday. https://rubygems.org/gems/async-http-faraday points to https://github.com/socketry/async-http but it should probably be https://github.com/socketry/async-http-faraday. I will close this issue here.
